logging:
  level:
    org:
      springframework: DEBUG
    com:
      springKotlinAuthentication: DEBUG
    web: DEBUG
  pattern:
    console:
      color: true
      date-time: "yyyy-MM-dd HH:mm:ss"
      level: "%5p"
      logger: "%c"
      message: "%m%n"

spring:
  security:
    jwt:
      secret-key: 916rXznLgpdWRQBpaHbo8tvgkKN8fzwlpdSOvOu9uYc
      expiration: 86400000  # 1 hour
      refresh-token:
        expiration: 1209600000  # 14 days

  datasource:
    url: jdbc:mysql://localhost:3307/test_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true